id: 'First Gate'
model_path: '/data/models/first_gate_march/xception/model_max_acc_1gpu.h5'
model_map_json: 'example/first_gate_model_map.json'
threshold:
  threshold_class: 3
  threshold_prob: 0.1
  trigger_classes: [2]
pass_through: [3]
batch_size: 32
