#!/usr/bin/env bash
. script/env
set -xe

autopep8 --in-place --recursive --max-line-length 1000 --aggressive --ignore E402 studio tests
autoflake --in-place --remove-unused-variables --remove-all-unused-imports --recursive studio tests